# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email:
    recipients:
      - h.neth@uni.kn
      - contact.riskyr@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
