## plot_mosaic.R | riskyR
## 2018 01 25
## -----------------------------------------------
## Plot mosaicplot that expresses freq as area
## (size and proportion)

## -----------------------------------------------
## Dependencies:

# library("vcd") # moved to "Imports:" in in DESCRIPTION!
# library("grid")

## -----------------------------------------------
## plot_mosaic: Plot mosaic plot (with "vcd" and "grid")
## using only necessary arguments with good defaults:

## Assuming that df of popu is known [see comp_popu()]

## -----------------------------------------------

#' Plot a mosaic plot of population frequencies.
#'
#' \code{plot_mosaic} visualizes a mosaic plot that
#' represents the proportions of frequencies in the current
#' population \code{\link{popu}} as relatives sizes of
#' rectangular areas.
#'
#' Corresponding rectangles can be visualized by
#' opting for vertical rectangles (by selecting
#' the option \code{box = "vr"}) in \code{\link{plot_tree}}.
#'
#' \code{plot_mosaic} requires and uses the R packages "vcd" and
#' "grid" (\code{library("vcd", "grid")}).
#'
#' @examples
#' plot_mosaic()
#' plot_mosaic(title.lbl = "")
#' plot_mosaic(vsplit = FALSE)
#' plot_mosaic(title.lbl = "My favorite scenario", col.sdt = "goldenrod")
#'
#' @seealso
#' The corresponding data frame \code{\link{popu}}
#' is generated by \code{\link{comp_popu}};
#' \code{\link{num}} for basic numeric parameters;
#' \code{\link{txt}} for current text settings;
#' \code{\link{pal}} for current color settings

plot_mosaic <- function(pop = popu,
                        vsplit = TRUE, # option: toggle vertical vs. horizontal split in plot
                        title.lbl = txt$scen.lbl,
                        col.sdt = pal[4:7]
) {

  ## Get probabilities from global numeric parameters (num):
  prev <- num$prev
  sens <- num$sens
  spec <- num$spec

  ## Define plot area:
  # plot(0, type = 'n')

  ## Text labels:
  if (nchar(title.lbl) > 0) { title.lbl <- paste0(title.lbl, ":\n") }  # put on top (in separate line)
  cur.title.lbl <- paste0(title.lbl, "Mosaic plot") # , "(N = ", N, ")")
  cur.par.lbl <-  paste0("(", "prev = ", as_pc(prev), "%, ", "sens = ", as_pc(sens), "%, ", "spec = ", as_pc(spec), "%)")

  ## Mosaic plot:

  if (vsplit) {

    ## (a) vertical split:
    vcd::mosaic(Decision ~ Truth, data = pop,
                shade = TRUE, colorize = TRUE,
                split_vertical = TRUE,
                gp = grid::gpar(fill = matrix(data = col.sdt, nrow = 2, ncol = 2, byrow = TRUE)),
                main_gp = grid::gpar(fontsize = 12, fontface = 1, adj = 0),
                sub_gp = grid::gpar(fontsize = 10, fontface = 1, adj = 1),
                main = paste0(cur.title.lbl), #, "\n", cur.par.lbl),
                sub = paste0(cur.par.lbl)
                )
  }

  else {

    ## (b) horizontal split:
    vcd::mosaic(Truth ~ Decision, data = pop,
                shade = TRUE, colorize = TRUE,
                split_vertical = FALSE,
                gp = grid::gpar(fill = matrix(data = col.sdt, nrow = 2, ncol = 2, byrow = FALSE)),
                main_gp = grid::gpar(fontsize = 12, fontface = 1),
                sub_gp = grid::gpar(fontsize = 10, fontface = 1),
                main = paste0(cur.title.lbl), #, "\n", cur.par.lbl),
                sub = paste0(cur.par.lbl)
                )

  }

  ## Title and margin text:
  # title(cur.title.lbl, adj = 0.5, line = -0.5, font.main = 1) # (left, lowered, normal font)
  # mtext(cur.par.lbl, side = 1, line = 1, adj = 1, col = grey(.33, .99), cex = .90)

}

## Check:
# plot_mosaic()
# plot_mosaic(title.lbl = "")
# plot_mosaic(vsplit = FALSE)
# plot_mosaic(title.lbl = "Just testing", col.sdt = "goldenrod")

## -----------------------------------------------
## (+) ToDo:

## - make mosaic plot dependent on basic parameters
##   (i.e., compute comp_popu() from probabilities and N,
##    rather than providing it as input)?
## - add a simpler version that only shows cond.true vs. cond.false
## - adjust parameters (zero size and gap width)
## - add labels (frequencies) to plot?

## -----------------------------------------------
## eof.
